services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Qwerty@12345"
      ACCEPT_EULA: "Y"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mssql
