services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Qwerty@12345"
      ACCEPT_EULA: "Y"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=I_am_Hero;User=sa;Password=Qwerty@12345;TrustServerCertificate=True;"
    depends_on:
      - mssql
