//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_am_Hero_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I_am_Hero_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string AuthPageEmail {
            get {
                return ResourceManager.GetString("AuthPageEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string AuthPagePass {
            get {
                return ResourceManager.GetString("AuthPagePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign In.
        /// </summary>
        public static string AuthPageSignIn {
            get {
                return ResourceManager.GetString("AuthPageSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign Up.
        /// </summary>
        public static string AuthPageSignUp {
            get {
                return ResourceManager.GetString("AuthPageSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string CreateHeroCreateBtn {
            get {
                return ResourceManager.GetString("CreateHeroCreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сreate a name for your character:.
        /// </summary>
        public static string CreateHeroCreateName {
            get {
                return ResourceManager.GetString("CreateHeroCreateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are welcome, new player!.
        /// </summary>
        public static string CreateHeroTitle {
            get {
                return ResourceManager.GetString("CreateHeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t have an account?.
        /// </summary>
        public static string LoginPageNoAcc {
            get {
                return ResourceManager.GetString("LoginPageNoAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calendar.
        /// </summary>
        public static string MainPageCalendar {
            get {
                return ResourceManager.GetString("MainPageCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level.
        /// </summary>
        public static string MainPageLevel {
            get {
                return ResourceManager.GetString("MainPageLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Achievements.
        /// </summary>
        public static string MainPageMenuAchievements {
            get {
                return ResourceManager.GetString("MainPageMenuAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attributes.
        /// </summary>
        public static string MainPageMenuAttributes {
            get {
                return ResourceManager.GetString("MainPageMenuAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collapse.
        /// </summary>
        public static string MainPageMenuCollapse {
            get {
                return ResourceManager.GetString("MainPageMenuCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dailies.
        /// </summary>
        public static string MainPageMenuDailies {
            get {
                return ResourceManager.GetString("MainPageMenuDailies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dashboard.
        /// </summary>
        public static string MainPageMenuDashboard {
            get {
                return ResourceManager.GetString("MainPageMenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Effects.
        /// </summary>
        public static string MainPageMenuEffects {
            get {
                return ResourceManager.GetString("MainPageMenuEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        public static string MainPageMenuProfile {
            get {
                return ResourceManager.GetString("MainPageMenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Habbits.
        /// </summary>
        public static string MainPageMenuQuestHabbits {
            get {
                return ResourceManager.GetString("MainPageMenuQuestHabbits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quest Lines.
        /// </summary>
        public static string MainPageMenuQuestLines {
            get {
                return ResourceManager.GetString("MainPageMenuQuestLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quests.
        /// </summary>
        public static string MainPageMenuQuests {
            get {
                return ResourceManager.GetString("MainPageMenuQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skills.
        /// </summary>
        public static string MainPageMenuSkills {
            get {
                return ResourceManager.GetString("MainPageMenuSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string MainPageSettingsAbout {
            get {
                return ResourceManager.GetString("MainPageSettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level calculation type.
        /// </summary>
        public static string MainPageSettingsCalculationType {
            get {
                return ResourceManager.GetString("MainPageSettingsCalculationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string MainPageSettingsLanguage {
            get {
                return ResourceManager.GetString("MainPageSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log Out.
        /// </summary>
        public static string MainPageSettingsLogout {
            get {
                return ResourceManager.GetString("MainPageSettingsLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string MainPageSettingsLogoutCancel {
            get {
                return ResourceManager.GetString("MainPageSettingsLogoutCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log out.
        /// </summary>
        public static string MainPageSettingsLogoutConfirm {
            get {
                return ResourceManager.GetString("MainPageSettingsLogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to log out?.
        /// </summary>
        public static string MainPageSettingsLogoutTitle {
            get {
                return ResourceManager.GetString("MainPageSettingsLogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string MainPageSettingsModalClose {
            get {
                return ResourceManager.GetString("MainPageSettingsModalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string MainPageSettingsModalTitle {
            get {
                return ResourceManager.GetString("MainPageSettingsModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notifications.
        /// </summary>
        public static string MainPageSettingsNotifications {
            get {
                return ResourceManager.GetString("MainPageSettingsNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support developers.
        /// </summary>
        public static string MainPageSettingsSupport {
            get {
                return ResourceManager.GetString("MainPageSettingsSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm password.
        /// </summary>
        public static string RegisterPageConfirmPass {
            get {
                return ResourceManager.GetString("RegisterPageConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
    }
}
